<?php

return [

    'personal_info' => [
        'name' => 'Bagus Batra',
        'nickname' => 'Bagus',
        'title_id' => 'Senior Web Developer & Frontend Specialist',
        'title_en' => 'Senior Full-Stack & Frontend Architect',
        'tagline_id' => 'Membangun aplikasi web berkinerja tinggi, antarmuka elegan, dan arsitektur kode yang tangguh.',
        'tagline_en' => 'Crafting high-performance web applications, intuitive interfaces, and scalable front-end systems.',
        'bio_id' => 'Halo! Saya seorang Software Engineer dengan pengalaman 6+ tahun dalam ekosistem JavaScript & TypeScript modern (React, Next.js, Node.js, Tailwind CSS). Saya memiliki antusiasme mendalam pada performa web, desain sistem yang modular, dan micro-interactions yang mulus tanpa mengorbankan aksesibilitas.',
        'bio_en' => "Hi! I'm a software engineer with 6+ years of experience crafting fast, accessible, and delightful web products. I specialize in the modern TypeScript ecosystem (React, Next.js, Tailwind, Node.js, GraphQL) with a relentless focus on runtime performance and UI craftsmanship.",
        'location' => 'Jakarta & Bali, Indonesia (Available Remote Worldwide)',
        'email' => 'bagusbatr@gmail.com',
        'phone' => '+62 812-3456-7890',
        'github' => 'https://github.com/bagusbatra',
        'linkedin' => 'https://linkedin.com/in/bagusbatra',
        'twitter' => 'https://twitter.com/bagusbatra',
        'available_for_work' => true,
        'years_of_exp' => '6+',
        'completed_projects' => '45+',
        'client_satisfaction' => '99.4%',
        'open_source_contributions' => '320+',
        'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
        'secondary_avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    ],

    'social_links' => [
        [
            'platform' => 'GitHub',
            'name' => 'GitHub',
            'url' => 'https://github.com',
            'username' => '@bagusbatra',
            'icon' => 'Github',
            'bg_color' => 'hover:bg-slate-900 hover:text-white',
            'text_color' => 'text-slate-800',
            'description' => '30+ repositori publik & kontribusi open-source',
        ],
        [
            'platform' => 'LinkedIn',
            'name' => 'LinkedIn',
            'url' => 'https://linkedin.com',
            'username' => 'Bagus Batra',
            'icon' => 'Linkedin',
            'bg_color' => 'hover:bg-[#0A66C2] hover:text-white',
            'text_color' => 'text-[#0A66C2]',
            'description' => 'Koneksi profesional, artikel karier & rekomendasi',
        ],
        [
            'platform' => 'Twitter',
            'name' => 'X (Twitter)',
            'url' => 'https://twitter.com',
            'username' => '@bagusbatra',
            'icon' => 'Twitter',
            'bg_color' => 'hover:bg-black hover:text-white',
            'text_color' => 'text-slate-900',
            'description' => 'Berbagi tips kilat seputar React, CSS & UI engineering',
        ],
        [
            'platform' => 'YouTube',
            'name' => 'YouTube',
            'url' => 'https://youtube.com',
            'username' => 'Bagus Dev Journey',
            'icon' => 'Youtube',
            'bg_color' => 'hover:bg-[#FF0000] hover:text-white',
            'text_color' => 'text-[#FF0000]',
            'description' => 'Tutorial arsitektur web & live-coding showcase',
        ],
        [
            'platform' => 'Instagram',
            'name' => 'Instagram',
            'url' => 'https://instagram.com',
            'username' => '@bagusbatra',
            'icon' => 'Instagram',
            'bg_color' => 'hover:bg-[#E1306C] hover:text-white',
            'text_color' => 'text-[#E1306C]',
            'description' => 'Behind-the-scenes workflow, remote setup & tech gear',
        ],
        [
            'platform' => 'Email',
            'name' => 'Direct Email',
            'url' => 'mailto:bagusbatr@gmail.com',
            'username' => 'bagusbatr@gmail.com',
            'icon' => 'Mail',
            'bg_color' => 'hover:bg-indigo-600 hover:text-white',
            'text_color' => 'text-indigo-600',
            'description' => 'Respon cepat dalam kurun waktu < 24 jam',
        ],
    ],

];
